# Generated by Django 5.1.4 on 2025-01-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Идентификационный номер')),
                ('category', models.CharField(choices=[('алкоголь', 'Алкогольный'), ('безалкогольный', 'Неалкогольный'), ('сырье', 'Сырье'), ('оборудование', 'Оборудование'), ('расходные_материалы', 'Расходный материал')], max_length=20, verbose_name='Категория')),
                ('unit', models.CharField(choices=[('Штуки', 'Штуки'), ('Литр', 'Литр'), ('Кг', 'Кг')], max_length=10, verbose_name='Единица измерения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('норма', 'Норма'), ('брак', 'Брак')], default='норма', max_length=10, verbose_name='Состояние')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
