# Generated by Django 5.1.4 on 2025-01-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_produk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('address_registration', models.CharField(max_length=255, verbose_name='Адрес по прописке')),
                ('address_residence', models.CharField(max_length=255, verbose_name='Фактическое место жительства')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('passport_expiry_date', models.DateField(verbose_name='Срок действия')),
                ('phone_number_1', models.CharField(max_length=15, verbose_name='Контактный номер 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный номер 2')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='distributors/', verbose_name='Фото')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
            },
        ),
        migrations.CreateModel(
            name='ReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уникальный код')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('return_status', models.CharField(choices=[('normal', 'Норма'), ('defective', 'Брак')], max_length=50, verbose_name='Статус возврата')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_history', to='start_produk.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_produk.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История возврата',
                'verbose_name_plural': 'Истории возвратов',
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уникальный код')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_history', to='start_produk.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_produk.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История продаж',
                'verbose_name_plural': 'Истории продаж',
            },
        ),
    ]
